name: Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: homepage-artifact
          path: ~/artifacts/homepage

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ~/artifact/
