name: Deploy
on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: homepage-artifact
          path: ./artifacts/homepage

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./artifact/
