name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7.5.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - uses: nrwl/nx-set-shas@v2

      - run: pnpm nx workspace-lint
      - run: pnpm nx format:check
      - run: pnpm nx affected --target=lint --parallel=3
      - run: pnpm nx affected --target=test --parallel=3 --ci --code-coverage
      - run: pnpm nx affected --target=build --parallel=3 --prod
      
      - uses: actions/upload-artifact@v3
        name: Upload Homepage artifact
        with:
          name: homepage-artifact
          path: dist/apps/homepage/
